import { Footer } from "@/components/Footer";
import Navbar1 from "@/components/Navbar";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <Navbar1 />
                {children}
                <Footer />
            </body>
        </html>
    );
}
